base_model: openai/clip-vit-base-patch32
transform: Normalize
transform_params:
  # https://github.com/huggingface/transformers/blob/main/src/transformers/utils/constants.py
  mean: [0.48145466, 0.4578275, 0.40821073]
  std: [0.26862954, 0.26130258, 0.27577711]