device: cuda
# Model
base_model: null
projection_head: yes
prediction_head: [512, 2]
random_init: no
checkpoint: null
# Labeled Data
dataset: null
weighted_sampling: yes
# Unlabeled Data
unlabeled_data: null
unlabeled_ratio: 1
# Loss
loss_fn: CrossEntropyLoss
loss_params: {}
# Trainer
trainer: Supervised
# Optimizer
optimizer: AdamW
learning_rate: 0.0001
# Training
batch_size: 64
num_workers: 1
num_epochs: 100
# Evaluation
evaluator: Classification
eval_only: no
test_eval_freq: -1
eval_on_best_checkpoint: yes
# WandB
name: null
project: FACT
# Checkpointing
checkpoint_interval: 5
checkpoints_dir: null
monitor: balanced_accuracy
objective: maximize
num_saved: 2
resume: yes
# Early Stopping
early_stopping: yes
patience: 10
# FixMatch
tau: 0.95
llambda: 1
