device: cuda
# Model
base_model: laion/clap-htsat-unfused
projection_head: yes
prediction_head: [2]
random_init: yes
checkpoint: null
# Data
dataset: null
# Loss
loss_fn: CrossEntropyLoss
loss_params: {}
# Trainer
trainer: Supervised
# Optimizer
optimizer: AdamW
learning_rate: 0.0001
# Training
batch_size: 64
num_workers: 1
num_epochs: 100
# Evaluation
classification_metrics: no
clustering_metrics: no
target: predictions
test_eval_freq: -1
# WandB
name: null
project: FACT
# Checkpointing
checkpoint_interval: 1
checkpoints_dir: null
monitor: balanced_accuracy
objective: maximize
num_saved: 2
resume: yes
